publicHLSPath: webroot/hls
privateHLSPath: hls
webServerPort: 8080


extraUserInfoFileName: "/static/content.md"


videoSettings:
  # The length of a single segment of video.
  chunkLengthInSeconds: 4
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: abc123
  # The "Stream is offline" content displayed when a stream ends.
  offlineContent: static/offline.m4v

  # Determine the bitrate of your stream variants.
  # See https://github.com/gabek/owncast/blob/master/doc/configuration.md#video-quality for details.
  streamQualities:
    - low:
      # Higher the bitrate, the better it looks, but it requires more bandwidth to consume.
      videoBitrate: 400
      # Resize the width to something smaller.  scaledHeight is also an option.  Don't use both at once
      # unless you want to chang the aspect ratio of your video.
      scaledWidth: 600
      # Don't re-encode the audio.
      audioPassthrough: true
      # The slower the preset the higher quality the video is.
      # Select a preset from https://trac.ffmpeg.org/wiki/Encode/H.264
      # "superfast" and "ultrafast" are generally not recommended since they look bad.
      encoderPreset: veryfast

    - medium:
      videoBitrate: 800
      encoderPreset: fast

# Number of segments kept referenced in the HLS playlist
files:
  maxNumberInPlaylist: 4

# See https://owncast.online/docs/configuration/ for more details

instanceDetails:
  name: Owncast
  title: Owncast
  summary: "This is brief summary of whom you are or what your stream is. You can read more about it at owncast.online.  You can edit this description in your config file."

  logo:
    small: /img/logo128.png
    large: /img/logo256.png

  tags:
    - music
    - software
    - streaming
